//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheProject_Register01_onEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int JustId { get; set; }
        public int IdUser { get; set; }
        public string Domens { get; set; }
    
        public virtual Domen Domen { get; set; }
        public virtual User User { get; set; }
    }
}
